create table "public"."Tenants" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "first_name" character varying,
    "last_name" character varying,
    "phone_number" character varying
);


alter table "public"."Tenants" enable row level security;

CREATE UNIQUE INDEX "Tenants_pkey" ON public."Tenants" USING btree (id);

alter table "public"."Tenants" add constraint "Tenants_pkey" PRIMARY KEY using index "Tenants_pkey";


